### ISSUE TITLE
Add ability to highlight and output to command-line

### ISSUE THREAD

**Issue by johnkary** [jdorn/sql-formatter#33]
I'm wondering if you would be open to SQL Formatter supporting coloring output for the command-line in addition to the current HTML coloring?

I have a feeling the whitespace code would all work the same, but the syntax highlighting would instead be replaced with CLI coloring "tags" like: \e[1;36;40m

Is this something you would be willing to add? Or would you be open to accepting it into the project if someone submitted a pull request?

This idea came to me when working with Symfony2 and the DoctrineBundle and seeing SQL output to the CLI. I know this lib is already used in DoctrineBundle for the Symfony2 Web Debug Toolbar, but I wanted some syntax highlighting and nicer formatting in the output of `php app/console doctrine:schema:update --dump-sql`. I realize I could pipe it to something like the Python syntax highlighting package `pygments`, but I think a PHP-only solution would be better for others not wanting to install python and pip and pygments.

**Comment by Geolim4** [comment]
@jdorn It's great, but what if we want to keep the HTML format while running in Cli ?
You should an option like "$forceHtmlIOutput" and/or "forceCliOutput"
