### ISSUE TITLE
Please add PSR-4 compliance

### ISSUE THREAD

**Issue by andig** [jdorn/sql-formatter#91]

**Comment by stof** [comment]
This package contains a single class. What is the issue about the current setup ?

**Comment by andig** [comment]
I maybe mistaken, but if I want to use this class from a reusable component I'd need to do some guessing on the location of the vendor folder for requiring the class. With Psr-4 I could just "use" it without the guesswork and without any overhead on the formatters side?

**Comment by andig** [comment]
My mistake- I can just use the class from global namespace.
