### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by garak** [jdorn/sql-formatter#96]
* last commit on Aug 2015
* last release on Jan 2014
* 17 open issues
* 11 open PRs

maybe it's time to look for a new maintainer?

**Comment by Esysteme** [comment]
I think i will open a new one. because i did a lot of change too

**Comment by garak** [comment]
I'd love to hear some news from @jdorn

**Comment by greg0ire** [comment]
We started a fork at Doctrine: https://github.com/doctrine/sql-formatter Send PRs :)
